### ISSUE TITLE
use command "npm run dev" throw error

### ISSUE THREAD

**Issue by CodingGorit** [wechat-miniprogram/miniprogram-cli#6]
[23:52:22] Error: File not found with singular glob: C:\Users\Gorit\Desktop\fm-miniprogram-components\miniprogram_dev\package.json (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\Users\Gorit\Desktop\fm-miniprogram-components\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:467:12)
    at Glob._finish (C:\Users\Gorit\Desktop\fm-miniprogram-components\node_modules\glob\glob.js:194:8)
    at done (C:\Users\Gorit\Desktop\fm-miniprogram-components\node_modules\glob\glob.js:179:14)
    at Glob._processSimple2 (C:\Users\Gorit\Desktop\fm-miniprogram-components\node_modules\glob\glob.js:688:12)
    at C:\Users\Gorit\Desktop\fm-miniprogram-components\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\Users\Gorit\Desktop\fm-miniprogram-components\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\Users\Gorit\Desktop\fm-miniprogram-components\node_modules\glob\glob.js:764:12)

**Comment by CodingGorit** [comment]
> 
my node version is v14.15.3, npm version is v7.21.0

**Comment by CodingGorit** [comment]
yesterday, "glob" version is "7.2.0", today, it updated to "7.2.2" which lead to error ,need add  "glob": "7.2.0" in package.json to avoid error
